//Взаимодействия с элементами по атрибутам
$('a[download]').css('border', '1px solid red'); //ростой атребут
$('a[href="http://ya.ru"]').css('border', '1px solid red'); // поолное соотвецтвие
$('a[href!="http://ya.ru"]').css('border', '1px solid red'); // полное несоотвецтвия
$('a[href^="http"]').css('border', '1px solid red'); // начинается с ...
$('a[href$=".com"]').css('border', '1px solid red'); // заканчивается на ...
$('a[href*="google"]').css('border', '1px solid red'); // содержит ...
$('a[data-target|="main"]').css('border', '1px solid red'); // имеет префикс - ...
$('a[href][download]').css('border', '1px solid red'); // имеет одновременно несколько атрибутов